### ISSUE TITLE
Decide on unit testing framework

### ISSUE THREAD

**Issue by marci4** [ps2alerts/websocket#32]
We should decide on a unit testing framework.

Possibilities are 
- Jest
- Mocha
- Jasmine

**Comment by Hailot** [comment]
configuration and setup wise Jest is definitely the preferred of all of them. Mocha is extremely versatile but requires adding additional libraries for stuff like assertions..  imo we should use Jest

**Comment by marci4** [comment]
I am also in favor of jest!

**Comment by vostrnad** [comment]
I'm used to Jasmine but Jest seems to be very similar. It should work just fine.

**Comment by marci4** [comment]
@Maelstromeous you're fine with jasmine?

**Comment by vostrnad** [comment]
Despite using it myself, I feel I have to speak against Jasmine here. Jest seems to be much better maintained, and since we're going to be testing TypeScript code, I should mention that [ts-jest](https://www.npmjs.com/package/ts-jest) had its last release 18 days ago while [jasmine-ts](https://www.npmjs.com/package/jasmine-ts) hasn't seen a release for 2 years.

**Comment by Maelstromeous** [comment]
I thought the consensus was Jest?

**Comment by marci4** [comment]
My bad, I meant jest -.-

**Comment by marci4** [comment]
So jest it is :)
